using System.Threading.Tasks;

namespace SwAIvyn.Services.VectorStore
{
    /// <summary>
    /// Interface for generating vector embeddings from text
    /// </summary>
    public interface IEmbeddingService
    {
        /// <summary>
        /// Generates a vector embedding for the given text
        /// </summary>
        /// <param name="text">Input text</param>
        /// <returns>Vector embedding</returns>
        Task<float[]> EmbedTextAsync(string text);

        /// <summary>
        /// Gets the dimensions of the embeddings generated by this service
        /// </summary>
        int Dimensions { get; }
    }
}
